### ISSUE TITLE
Gestion des items

### ISSUE THREAD

**Issue by lgmb10** [lgmb10/workshop-equipe13#7]
Fonctionnalités :
- Ajouter des items qui apparaissent de façon aléatoire et qui agissent sur le jeu ou sur le joueur

Liste des items et de leur fonctions : 
- ( à définir)

**Comment by Lekta23** [comment]
Dev terminé, ajout d'une étoile qui fait gagner 5 points, potion qui ralenti la vitesse et cœur pour gagner une vie
